### ISSUE TITLE
Add auto-updating

### ISSUE THREAD

**Issue by oskarkrawczyk** [oskarkrawczyk/overcast-mac#2]
Preferably it should just pick up the newest release from GH Releases.

**Comment by terkelg** [comment]
Yes, it's pretty easy, you can see what I did in Ramme: 
https://github.com/terkelg/ramme/blob/master/version.js

I can implement this if you like

**Comment by oskarkrawczyk** [comment]
@terkelg If you have the time, that would be great! Would give me the time to focus on other things from the todo.

**Comment by oskarkrawczyk** [comment]
This project is no longer maintained. Closing.
